student_height = (input("Enter the list of height of students ")).split(", ")
print(student_height)
student_heights = (input("Enter the list of height of student. ")).split()
print(student_heights)
# integer = int(student_height)
# total_height = sum(integer)
# number_of_student = len(integer)
# average_height = round(total_height/integer)
# print(average_height)
