print(''' 
CHALAT VIMAAN KOLAHAL HOI 
JAI RUGHUVIR KAHAI SB KOI 
PARAM SUKHAD CHALI TRIBIDH BYARI
SGAR SAR SARI NIRMAL BARI ''')

print(''' 
NATH SAKAL SAMPADA TUMHARI 
NATH SAKAL SAMPADA TUMHARI 
MAI SEVAK SAMET SUT NARI 
MAI SEVAK SAMET SUT NARI 
KARABA SADA LARIKAN PAR CHHOHU 
KARABA SADA LARIKAN PAR CHHOHU 
DARSHAN DET RAHAB MUNI MOHU
DARSHAN DET RAHAB MUNI MOHU. ''')

print('''
SITARAM RAM RAM
SITARAM RAM RAM
SITARAM RAM RAM 
SITARAM CHARAN RATI MORE 
ANUDIN BADHAU ANUGRAH TORE
JEHI VIDHI NATH HOI HIT MORA 
KARAHU SOBEGI DAS MAI TORA
SITARAM RAM RAM 
SITARAM RAM RAM 
SITARAM RAM RAM
''')

print('''
BHAYE PRAGAT KRIPALA DINDYALA KAUSHALYA HITKARI
HARSHIT MAHTARI MUNI MAN HARI ADABHUT RUP NIHARI 
LOCHAN ABHIRAMA TANU GHANSHYAMA NIDH AAYUDH BHUJ CHARI
BHUSHAN VANMALA NAYAN VISHALA SHOBHA SINDHU KHARARI
KAH DUI KAR JORI ASTUTI TORI KEHI VIDHI KARAHU ANANTA 
MAYA GUN GYANA TIT AMANA VED PURAN BHANANTA
KARUNA SUKH SAGAR SAB GUN AAGAR JEHI GAVAHI SHARUTI SANTA
SO MAM HIT LAGI JAN ANURAGI BHAYAHU PRAGAT SHIRIKANTA
BRAHMAND NIKAYA NIRMIT MAYA ROM ROM PRATI VED KAHE
MAM UR SO BASI YAH UPHASI SUNAT DHIR MATI THIR NA RAHE
UPJA JAB GYANA PRABHU MUSKANA CHARIT BAHUT VIDHI KIN CHAHE
KAHI KATHA SUHAI MATU BUJHAI JEHI PRAKAR SUT PREM LAHE
MATA PUNI BOLI SOMATI DOLI TAJAHU TAT YAH RUPA
KI JAI SHISHULILA ATIPRIYA SHILA YAH SUKH PARAM ANUPA
SUNI VACHAN SUJANA RODAN THANA HOI BALAK SURBHUPA
YAH CHARIT JE GAVAHI HARI PAD PAVAHI TE NA PARAHI BHAVKUPA
(VIPRA DHENU SUR SANT HIT LIN MNUJ AVATAR
NIJ ICHCHHA NIRMIT TANU MAYA GUN GO PAAR )''')